import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import TelegramWapper from "@/modules/TelegramWapper";


const inter = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TelegramWapper>
        {children}
        </TelegramWapper>
      </body>
    </html>
  );
}
